Modify syntax to specify remote and target branch
- copied the syntax from push
- updated usage and README to explain the syntax

[close #4]

diff --git a/git-land b/git-land
--- a/git-land
+++ b/git-land
@@ -7,11 +7,9 @@
 # http://www.apache.org/licenses/LICENSE-2.0
 
 project_root=`echo $(git rev-parse --show-toplevel)`
-lockfile=$project_root/.git-land-in-progress
-merge_branch="$1"
-
 # This lockfile exists primarily so that other automation, such as file change
 # monitoring, can react to the fact that this process is running.
+lockfile=$project_root/.git-land-in-progress
 touch $lockfile
 
 function exit_and_cleanup() {
@@ -19,13 +17,38 @@ function exit_and_cleanup() {
   exit $1
 }
 
-if [ -z "$merge_branch" ]; then
+function usage() {
+  echo "$1"
   echo ""
-  echo "Usage: git land <pull request number>"
-  echo "       git land <branch>"
+  echo "Usage: git land [<remote>] <pull request number>[:<target branch>]"
+  echo "       git land [<remote>] <branch>[:<target branch>]"
+  echo ""
+  echo " <remote>: the remote repo (default: origin)"
+  echo " <pull request number>: a pull request to merge and close"
+  echo " <branch>: a branch to merge and close"
+  echo " <target branch>: the branch to merge to (default: master)"
+  echo ""
+  echo "Examples:"
+  echo "  git land origin 23:master"
+  echo "  git land my-feature"
+  echo "  git land my-feature:target-branch"
   echo ""
   exit_and_cleanup 1
-fi
+}
+
+
+args=()
+# Parse args
+while [[ $# > 0 ]]; do
+  arg="$1"
+
+  case $arg in
+    *)
+      args[${#args[@]}]=$arg
+      shift
+      ;;
+  esac
+done
 
 # set upstream remote, defaulting to origin
 remote=$(git config git-land.remote)
@@ -33,26 +56,53 @@ if [ -z "$remote" ]; then
   remote='origin'
 fi
 
+merge_branch=""
+target_branch="master"
+
+case ${#args[@]} in
+  0)
+    usage "specified no args"
+    ;;
+  1)
+    merge_branch=${args[0]}
+    ;;
+  2)
+    remote=${args[0]}
+    merge_branch=${args[1]}
+    ;;
+  *)
+    usage "too many args"
+    ;;
+esac
+
+# the branch specifier is source:target, but you can also just say source for short,
+# in which case, target defaults to "master"
+if [[ $merge_branch =~ ^[^:]+:[^:]+$ ]]; then
+  branches=($(echo $arg | tr ':' '\n')) # split on ':' into an array
+  merge_branch=${branches[0]}
+  target_branch=${branches[1]}
+fi
+
 # set merge branch if merging a PR
-if [[ $1 =~ ^[0-9]+$ ]]; then
+if [[ $merge_branch =~ ^[0-9]+$ ]]; then
   pr=$merge_branch
   merge_branch="$remote/pr/$pr"
 fi
 
-read -r -p "Are you sure you want to merge $merge_branch into $remote/master? [Y/n] " response
+read -r -p "Are you sure you want to merge $merge_branch into $remote/$target_branch? [Y/n] " response
 if [[ ! ($response = '' || $response =~ ^([yY][eE][sS]|[yY])$) ]]; then
   exit_and_cleanup 1
 fi
 
-# sync local master with latest on github
-if ! (git checkout master && git fetch $remote && git reset --hard $remote/master); then
-  echo 'Could not sync local master with main repo'
+# sync local $target_branch with latest on github
+if ! (git checkout $target_branch && git fetch $remote && git reset --hard $remote/$target_branch); then
+  echo "Could not sync local $target_branch with main repo"
   exit_and_cleanup $?
 fi
 
 # rebase and squash
-if ! (git checkout $merge_branch && git rebase -i master); then
-  echo "Could not checkout or rebase $merge_branch on master"
+if ! (git checkout $merge_branch && git rebase -i $target_branch); then
+  echo "Could not checkout or rebase $merge_branch on $target_branch"
   exit_and_cleanup $?
 fi
 
@@ -69,10 +119,10 @@ fi
 
 # merge the PR and push
 head=$(git rev-parse HEAD)
-if ! (git checkout master && git merge --ff-only $head); then
-  echo "Could not fast-forward merge $merge_branch into master"
+if ! (git checkout $target_branch && git merge --ff-only $head); then
+  echo "Could not fast-forward merge $merge_branch into $target_branch"
   exit_and_cleanup $?
 fi
 
-git push $remote master
+git push $remote $target_branch
 exit_and_cleanup $?
